# Generated by Django 3.0.5 on 2020-12-11 12:55

from django.db import migrations, models
import panel.models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPULogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('usage', models.FloatField(default=panel.models.Server_stat.cpu_percent)),
            ],
        ),
    ]
